# ==========================
# Evaluation configuration
# ==========================
experiment:
  model_name: "BasicUNet"
  run_name: "baseline"
  save_root: "results"

data:
  test_images: "/media/ttoxopeus/datasets/nnUNet_raw/Dataset200_ACDC/imagesTs"
  test_labels: "/media/ttoxopeus/datasets/nnUNet_raw/Dataset200_ACDC/labelsTs"
  image_size: [256, 256]

model:
  in_ch: 1
  out_ch: 4
  features: [32, 64, 128, 256]

training:
  device: "cuda"

evaluation:
  checkpoint: "results/BasicUNet/baseline/final_model.pth"
  save_dir: "results/BasicUNet/baseline/evaluation_test"
  num_slices_per_volume: 30
  num_visuals: 5
