# prune.yaml
prune:
  method: l1
  global_prune: false

  # Default ratio if not specified per block
  default_ratio: 0.3

  # Per-block pruning ratios
  ratios:
    encoders.0.net: 0.1
    encoders.1.net: 0.2
    encoders.2.net: 0.3
    encoders.3.net: 0.4
    bottleneck.net: 0.5
    decoders.0.net: 0.4
    decoders.1.net: 0.3
    decoders.2.net: 0.2
    decoders.3.net: 0.1
